# @package _global_
# WildTrack Full Dataset 3DGUT app config.
# 完整数据集训练配置

defaults:
  - /base_gs
  - /dataset: wildtrack
  - /initialization: random
  - /render: 3dgut
  - _self_

path: /data02/zhangrunxiang/data/Wildtrack
out_dir: ./runs
val_frequency: 1000
n_iterations: 30000

model:
  background:
    color: black

initialization:
  num_gaussians: 50000
  xyz_min: -700.0
  xyz_max: 2100.0

dataset:
  downsample_factor: 4
  test_split_interval: 5

optimizer:
  lr: 0.001
